#pragma once

#include "default.defines.h"

#ifndef _MESSAGE_TOOL_WND_AS_DLL
#	define _MESSAGE_TOOL_WND_AS_DLL 1
#endif

#if (_MESSAGE_TOOL_WND_AS_DLL)

#	ifdef _EXPORTS_MESSAGE_TOOL_WND
#		define AFX_EXT_CLASS_MESSAGE_TOOL_WND	AFX_CLASS_EXPORT
#		define AFX_EXT_API_MESSAGE_TOOL_WND		AFX_API_EXPORT
#		define AFX_EXT_DATA_MESSAGE_TOOL_WND	AFX_DATA_EXPORT
#	else 
#		define AFX_EXT_CLASS_MESSAGE_TOOL_WND	AFX_CLASS_IMPORT
#		define AFX_EXT_API_MESSAGE_TOOL_WND		AFX_API_IMPORT
#		define AFX_EXT_DATA_MESSAGE_TOOL_WND	AFX_DATA_IMPORT
		__IMPORT_MOCHA_LIB__(MessageToolWnd)
#	endif

#else	// _MESSAGE_TOOL_WND_AS_DLL

#	define AFX_EXT_CLASS_MESSAGE_TOOL_WND
#	define AFX_EXT_API_MESSAGE_TOOL_WND
#	define AFX_EXT_DATA_MESSAGE_TOOL_WND

#endif
