#pragma once

#include "default.defines.h"

#ifndef _FRAME_GRABBER_AS_DLL
#	define _FRAME_GRABBER_AS_DLL 1
#endif

#if (_FRAME_GRABBER_AS_DLL)

#	ifdef _EXPORTS_FRAME_GRABBER
#		define AFX_EXT_CLASS_FRAME_GRABBER	AFX_CLASS_EXPORT
#		define AFX_EXT_API_FRAME_GRABBER	AFX_API_EXPORT
#		define AFX_EXT_DATA_FRAME_GRABBER	AFX_DATA_EXPORT
#	else 
#		define AFX_EXT_CLASS_FRAME_GRABBER	AFX_CLASS_IMPORT
#		define AFX_EXT_API_FRAME_GRABBER	AFX_API_IMPORT
#		define AFX_EXT_DATA_FRAME_GRABBER	AFX_DATA_IMPORT
		__IMPORT_MOCHA_LIB__(FrameGrabber)
#	endif

#else	// _FRAME_GRABBER_AS_DLL

#	define AFX_EXT_CLASS_FRAME_GRABBER
#	define AFX_EXT_API_FRAME_GRABBER
#	define AFX_EXT_DATA_FRAME_GRABBER

#endif
