#pragma once

#include "default.defines.h"

#ifndef _MIPSERVER_UI_AS_DLL
#	define _MIPSERVER_UI_AS_DLL 1
#endif

#if (_MIPSERVER_UI_AS_DLL)

#	ifdef _EXPORTS_MIPSERVER_UI
#		define AFX_EXT_CLASS_MIPSERVER_UI	AFX_CLASS_EXPORT
#		define AFX_EXT_API_MIPSERVER_UI		AFX_API_EXPORT
#		define AFX_EXT_DATA_MIPSERVER_UI	AFX_DATA_EXPORT
#	else 
#		define AFX_EXT_CLASS_MIPSERVER_UI	AFX_CLASS_IMPORT
#		define AFX_EXT_API_MIPSERVER_UI		AFX_API_IMPORT
#		define AFX_EXT_DATA_MIPSERVER_UI	AFX_DATA_IMPORT
		__IMPORT_MOCHA_LIB__(MIPServerUI)
#	endif

#else	// _MIPSERVER_UI_AS_DLL

#	define AFX_EXT_CLASS_MIPSERVER_UI
#	define AFX_EXT_API_MIPSERVER_UI
#	define AFX_EXT_DATA_MIPSERVER_UI

#endif
