//=============================================================================
//
// This file is automatically generated from msic::DStringTable.
// Do NOT edit manually.
//
//=============================================================================

#pragma once

#define IDS_START                                          ((int)  0)
#define IDS_ITEM_0                                         ((int)  1)
#define IDS_ITEM_1                                         ((int)  2)
#define IDS_ITEM_2                                         ((int)  3)
#define IDS_ITEM_3                                         ((int)  4)
#define IDS_ITEM_4                                         ((int)  5)
#define IDS_ITEM_5                                         ((int)  6)
#define IDS_ITEM_6                                         ((int)  7)
#define IDS_ITEM_7                                         ((int)  8)
#define IDS_ITEM_8                                         ((int)  9)
#define IDS_ITEM_9                                         ((int) 10)
#define IDS_ITEM_10                                        ((int) 11)
#define IDS_LASER_RECIPE_1                                 ((int) 12)
#define IDS_LASER_RECIPE_2                                 ((int) 13)
#define IDS_LASER_RECIPE_3                                 ((int) 14)
#define IDS_LASER_RECIPE_4                                 ((int) 15)
#define IDS_LASER_RECIPE_5                                 ((int) 16)
#define IDS_LASER_RECIPE_6                                 ((int) 17)
#define IDS_LASER_RECIPE_7                                 ((int) 18)
#define IDS_LASER_RECIPE_8                                 ((int) 19)
#define IDS_LASER_RECIPE_9                                 ((int) 20)
#define IDS_LASER_RECIPE_10                                ((int) 21)
#define IDS_LASER_RECIPE_11                                ((int) 22)
#define IDS_LASER_RECIPE_12                                ((int) 23)
#define IDS_LASER_RECIPE_13                                ((int) 24)
#define IDS_LASER_RECIPE_14                                ((int) 25)
#define IDS_LASER_RECIPE_15                                ((int) 26)
#define IDS_LASER_RECIPE_16                                ((int) 27)
#define IDS_EX                                             ((int) 28)

#define sIDS_START                                         "IDS_START"
#define sIDS_ITEM_0                                        "IDS_ITEM_0"
#define sIDS_ITEM_1                                        "IDS_ITEM_1"
#define sIDS_ITEM_2                                        "IDS_ITEM_2"
#define sIDS_ITEM_3                                        "IDS_ITEM_3"
#define sIDS_ITEM_4                                        "IDS_ITEM_4"
#define sIDS_ITEM_5                                        "IDS_ITEM_5"
#define sIDS_ITEM_6                                        "IDS_ITEM_6"
#define sIDS_ITEM_7                                        "IDS_ITEM_7"
#define sIDS_ITEM_8                                        "IDS_ITEM_8"
#define sIDS_ITEM_9                                        "IDS_ITEM_9"
#define sIDS_ITEM_10                                       "IDS_ITEM_10"
#define sIDS_LASER_RECIPE_1                                "IDS_LASER_RECIPE_1"
#define sIDS_LASER_RECIPE_2                                "IDS_LASER_RECIPE_2"
#define sIDS_LASER_RECIPE_3                                "IDS_LASER_RECIPE_3"
#define sIDS_LASER_RECIPE_4                                "IDS_LASER_RECIPE_4"
#define sIDS_LASER_RECIPE_5                                "IDS_LASER_RECIPE_5"
#define sIDS_LASER_RECIPE_6                                "IDS_LASER_RECIPE_6"
#define sIDS_LASER_RECIPE_7                                "IDS_LASER_RECIPE_7"
#define sIDS_LASER_RECIPE_8                                "IDS_LASER_RECIPE_8"
#define sIDS_LASER_RECIPE_9                                "IDS_LASER_RECIPE_9"
#define sIDS_LASER_RECIPE_10                               "IDS_LASER_RECIPE_10"
#define sIDS_LASER_RECIPE_11                               "IDS_LASER_RECIPE_11"
#define sIDS_LASER_RECIPE_12                               "IDS_LASER_RECIPE_12"
#define sIDS_LASER_RECIPE_13                               "IDS_LASER_RECIPE_13"
#define sIDS_LASER_RECIPE_14                               "IDS_LASER_RECIPE_14"
#define sIDS_LASER_RECIPE_15                               "IDS_LASER_RECIPE_15"
#define sIDS_LASER_RECIPE_16                               "IDS_LASER_RECIPE_16"
#define sIDS_EX                                            "IDS_EX"

